Errors during combine process now output to stderr

diff --git a/tools/combine b/tools/combine
--- a/tools/combine
+++ b/tools/combine
@@ -72,11 +72,11 @@ tpl_footer()
 
 # ensure we can locate our templates (should be in the /tools dir)
 if [ ! -f "$TPL_PATH" ]; then
-    echo "Error: combine.tpl not found ($TPL_PATH)"
+    echo "Error: combine.tpl not found ($TPL_PATH)" >&2
     exit 1
 fi
 if [ ! -f "$TPL_PATH" ]; then
-    echo "Error: license.tpl not found ($TPL_PATH)"
+    echo "Error: license.tpl not found ($TPL_PATH)" >&2
     exit 1
 fi
 
@@ -89,7 +89,7 @@ for module in $CAT_MODS; do
     filename="$PATH_LIB/$module.$MODULE_EXT"
 
     if [ ! -f "$filename" ]; then
-        echo "Error: module $module not found ($filename)"
+        echo "Error: module $module not found ($filename)" >&2
         exit 2
     fi
 
